### ISSUE TITLE
How to setup shape size while training ??

### ISSUE THREAD

**Issue by sudip550** [ARajgor/cp-vton-plus#2]
I am getting errors while using pre-trained model so How to setup shape size while training ??

**Comment by ARajgor** [comment]
> I am getting errors while using pre-trained model so How to setup shape size while training ??


Can you explain in more details?

**Comment by sudip550** [comment]
> > I am getting errors while using pre-trained model so How to setup shape size while training ??
> 
> Can you explain in more details?

I am getting this error = Namespace(name='GMM', dress_type='dresses', gpu_ids='', workers=4, batch_size=4, dataroot='./../result', datamode='test', stage='GMM', data_list='./../result/inference_dress.txt', fine_width=384, fine_height=512, radius=5, grid_size=10, tensorboard_dir='tensorboard', result_dir='result', checkpoint='./../../gdrive/MyDrive/gmm_final.pth', display_count=1, shuffle=False)
Start to test stage: GMM, named: GMM!
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
initialization method [normal]
initialization method [normal]
Traceback (most recent call last):
  File "/content/virtual-try-on-app/network/test.py", line 231, in <module>
    main()
  File "/content/virtual-try-on-app/network/test.py", line 215, in main
    load_checkpoint(model, opt.checkpoint)
  File "/content/virtual-try-on-app/network/networks.py", line 556, in load_checkpoint
    model.load_state_dict(torch.load(checkpoint_path))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GMM:
	size mismatch for regression.conv.0.weight: copying a param with shape torch.Size([512, 192, 4, 4]) from checkpoint, the shape in current model is torch.Size([512, 768, 4, 4]).
	size mismatch for regression.linear.weight: copying a param with shape torch.Size([50, 768]) from checkpoint, the shape in current model is torch.Size([200, 3072]).
	size mismatch for regression.linear.bias: copying a param with shape torch.Size([50]) from checkpoint, the shape in current model is torch.Size([200]).

**Comment by ARajgor** [comment]
I think you change something within the original code. But using the given data set for training all images are been the size of 192x256 pixels.
If you are trying to train with your custom dataset then I'll recommend you to change the shape of images.

**Comment by sudip550** [comment]
i want to talk you with some problems....

**Comment by ARajgor** [comment]
write it here. and please be more precise.

**Comment by sudip550** [comment]
i want to use this notebook = https://github.com/felicia-puzone/virtual-try-on-app

but they have not provided gmm and tom files. and when i use our pretrained models then i am getting error..

please help..

**Comment by ARajgor** [comment]
If you find difficulty in their project raise the issue there. The project structure is different so I can't help.

**Comment by sudip550** [comment]
> If you find difficulty in their project raise the issue there. The project structure is different so I can't help.

they are not responding....... please ...

**Comment by ARajgor** [comment]
Then I can't help. You are having a problem with (my) this repo. Then feel free to ask. other than that I can't do much for you. they may be change the code or implement their logic so

**Comment by sudip550** [comment]
> Then I can't help. if you are having a problem with (my) this repo. Then feel free to ask. other than that I can't do much for you. they may change the code or implement their logic so

ok sir.... thank you
